version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      # username is sa
      SA_PASSWORD: "very_cool_password_ok"
      ACCEPT_EULA: "Y"
