name: Configure CosmosDB

on:
  workflow_call:
    inputs:
      cosmos-db-account:
        required: true
        type: string
    secrets:
      AZURE_RESOURCE_GROUP:
        required: true
      AZURE_CREDENTIALS:
        required: true
      AZURE_SUBSCRIPTION_ID:

jobs:
  provision-identity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if ${{ inputs.cosmos-db-account }} account exists
      id: cosmos-db-check
      run: |
        echo "DB_EXISTS=$(az cosmosdb check-name-exists --name ${{ inputs.cosmos-db-account }})" >> $GITHUB_ENV

    - name: Create CosmosDB account if it doesn't exist
      if: ${{ env.DB_EXISTS == 'false' }}
      run: |
        az cosmosdb create --name ${{ inputs.cosmos-db-account }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}